version: "3.9"

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    container_name: api

  sqlpad:
    image: sqlpad/sqlpad:5
    ports:
      - '4000:3000'
    environment:
      - SQLPAD_ADMIN=admin
      - SQLPAD_ADMIN_PASSWORD=admin
      - SQLPAD_SEED_DATA_PATH=/etc/sqlpad/seed-data
      - SQLPAD_CONNECTIONS__pgdemo__name=KaraokeOK DB
      - SQLPAD_CONNECTIONS__pgdemo__driver=postgres
      - SQLPAD_CONNECTIONS__pgdemo__host=db
      - SQLPAD_CONNECTIONS__pgdemo__database=postgres
      - SQLPAD_CONNECTIONS__pgdemo__username=postgres
      - SQLPAD_CONNECTIONS__pgdemo__password=postgres
    restart: always
    container_name: sqlpad

volumes:
  postgres_data:
