# Generated by Django 4.0.1 on 2022-01-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
