# Generated by Django 4.0.1 on 2022-02-06 20:26
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeok', '0002_alter_song_thumbnail_url'),
    ]

    operations = [
        UnaccentExtension(),
    ]
