# Generated by Django 4.0.1 on 2022-02-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeok', '0005_alter_proposal_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='song',
        ),
    ]
