# Generated by Django 4.0.2 on 2022-02-27 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeok', '0009_auto_20220220_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
