# Generated by Django 4.0.2 on 2022-02-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeok', '0009_auto_20220220_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
