# Generated by Django 4.0.2 on 2022-09-25 22:56
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from karaokeok.models import Feedback, Proposal


def add_receiving_email_permissions(apps, schema_editor):
    content_type = ContentType.objects.get_for_model(Feedback)
    Permission.objects.create(
        codename='can_receive_feedback',
        name='Can receive feedback by emails',
        content_type=content_type,
    )

    content_type = ContentType.objects.get_for_model(Proposal)
    Permission.objects.create(
        codename='can_receive_proposal',
        name='Can receive proposal by emails',
        content_type=content_type,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeok', '0010_proposal_updated_at'),
    ]

    operations = [
        migrations.RunPython(add_receiving_email_permissions, reverse_code=migrations.RunPython.noop),
    ]
