# Generated by Django 4.0.2 on 2022-09-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeok', '0011_add_receiving_email_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='song_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
