# Generated by Django 4.0.2 on 2022-09-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaokeok', '0012_proposal_song_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='song_info',
            field=models.JSONField(blank=True, help_text='Song info to be added in the library.json file', null=True),
        ),
    ]
